spring:
  application:
    name: Recipe Kit

  datasource:
    url: jdbc:postgresql://localhost:5432/recipekit
    username: postgres
    password: Shashank2004@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
    secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGtleSB3aGljaCBpcyBvdmVyIDY0IGJ5dGVzIGxvbmcgdG8gc3VwcG9ydCBIUzUxMg==
